add unit tests
jqln-0/coolstreambot pull request #9
Opened 2021-09-15 20:21 UTC by eiais

2021-09-17 11:27 UTC, jqln-0 commented
yaml

yes,
*all*
my
lovers

2021-09-20 22:05 UTC, jqln-0 requested changes
```   ,_____ ,
  ,._ ,_. 7\
 j `-'     /
 |o_, o    \
.`_y_`-,'   !
|/   `, `._ `-,
|_     \   _.'*\
  >--,-'`-'*_*'``---.
  |\_* _*'-'         '
 /    `               \
 \.         _ .       /
  '`._     /   )     /
   \  |`-,-|  /c-'7 /
    ) \ (_,| |   / (_
   ((_/   ((_;)  \_)))       ```

2021-09-20 22:05 UTC, jqln-0 commented on vendor/github.com/davecgh/go-spew/LICENSE
> +Copyright (c) 2012-2016 Dave Collins <dave@davec.name>
delete this, fuck copyright

2021-09-20 22:05 UTC, jqln-0 commented on vendor/github.com/pmezard/go-difflib/LICENSE
> +Copyright (c) 2013, Patrick Mezard
i wrote this now

2021-09-20 22:05 UTC, jqln-0 commented on vendor/github.com/stretchr/testify/LICENSE
> +Copyright (c) 2012-2020 Mat Ryer, Tyler Bunnell and contributors.
i wrote this too. please delete this libelous text.

2021-09-20 22:05 UTC, jqln-0 commented on vendor/gopkg.in/yaml.v3/LICENSE
> +This project is covered by two different licenses: MIT and Apache.
'apache'?

no thank u, no cultural appropriation here

2021-09-20 22:05 UTC, jqln-0 commented on vendor/gopkg.in/yaml.v3/NOTICE
> +Copyright 2011-2016 Canonical Ltd.
i don't like the orange and purple colour scheme these lads use

2021-09-20 22:13 UTC, eiais commented
arf arf no licenses here

2021-09-23 08:12 UTC, jqln-0 approved these changes
good puppy

2021-09-23 08:12 UTC, merged